backend:
  name: git-gateway
  branch: main  # Replace 'main' with your repository's default branch

media_folder: "./uploads"  # Path where uploaded media files are stored in your repo
public_folder: "/./uploads"  # Public path for accessing media files

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }
