backend:
  name: git-gateway
  branch: main # Or the branch you are using

media_folder: "assets/uploads" # Path to upload images
public_folder: "/assets/uploads"

collections:
  - name: "pages" # Identifier, must be unique
    label: "Pages"
    folder: "" # Root folder of your site
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
