backend:
  name: git-gateway
  branch: main  # Ensure this matches your default branch

media_folder: "assets/uploads"  # Adjust if your media files are stored elsewhere
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
